import { p, g } from './lib.mjs';

export const GROUPS = ['Sell and get paid', 'Buy and spend', 'Run the business', 'Show up online', 'Work across your tools'];

export const AREAS = [
  /* ===== Sell and get paid ===== */
  {
    id: 'quotations', grp: 0, ic: 'doc', title: 'Quotations',
    lead: 'Draft in a minute. Issue with a yes.',
    intro: 'E drafts from your records and issues only when you say so.',
    ok: 'Issuing',
    groups: [
      g('Draft',
        p("Draft a quotation for [customer]: [quantity] × [product] at the stored price, valid until [date]. Ask me for anything missing. Don't issue it.", { top: 1 }),
        p('Change the quantity to three and show the new totals.'),
        p('Show me a preview.'),
        p('Cancel this draft.')),
      g('Issue',
        p('Show me the totals and preview. When I approve, issue it and give me the number and PDF.', { top: 1 })),
      g('Record the customer\'s answer',
        p('[Customer] accepted this quotation. Record it.'),
        p('Record that the customer rejected it because the price was too high.'),
        p('Which quotations are still open, accepted, rejected or expired?')),
      g('Turn it into an invoice',
        p("Convert the accepted quotation into an invoice draft. Don't issue it.", { top: 1 })),
    ],
    note: 'A draft has no number until you issue it. An issued quotation is frozen, so ask for a new draft to change it. If details conflict, E lists what is blocking in one message.',
  },
  {
    id: 'invoices', grp: 0, ic: 'receipt', title: 'Invoices and payments',
    lead: 'Issue, record payments, void and replace.',
    intro: 'E issues invoices and records the payments you tell it about.',
    ok: 'Issuing, voiding, each payment',
    groups: [
      g('Issue',
        p('Show me this invoice draft with its tax and total. Propose issuing it and wait for my OK.', { top: 1 }),
        p("Why can't this draft be issued yet?"),
        p('Give me the PDF of invoice [number].')),
      g('Record payments',
        p('How much does [customer] still owe on invoice [number]?', { top: 1 }),
        p('Record a payment of RM[amount] received on [date], reference [reference], against this invoice.', { top: 1 }),
        p('Record the exact remaining balance, reference [reference].')),
      g('Correct a mistake',
        p('This unpaid invoice went to the wrong customer. Propose voiding it and preparing a corrected replacement.'),
        p('Can I change the price on an issued invoice?', { n: 'E explains the correct route' })),
    ],
    note: 'E records payments; it never moves money. The same payment reference cannot be used twice. Paid invoices cannot be voided (E explains the credit-note route), and numbers are never reused.',
  },
  {
    id: 'customers', grp: 0, ic: 'people', title: 'Customers and products',
    lead: 'A name-card photo becomes a customer.',
    intro: 'E checks for an existing record before it creates a new one.',
    ok: 'Overwriting details, archiving',
    groups: [
      g('Add and find',
        p('Record this name card as a customer and contact. Use only what is printed, and check for duplicates first.', { top: 1, n: 'Attach a photo of the card' }),
        p('Do we already have a customer called [name]?'),
        p('Show me the billing address for [customer].')),
      g('Update safely',
        p("Propose changing [customer]'s billing address to [new address]. Wait for my OK.", { top: 1 }),
        p('Fill in the blanks on [customer] with this phone number, without changing anything confirmed.')),
      g('Products and bundles',
        p('Create product [A] at RM[price] and [B] at RM[price], then a package [name] of two A and one B for RM[price]. No duplicates.', { top: 1 })),
      g('From a form',
        p('Add this form lead to our customers. If it matches someone, only fill in blanks.')),
      g('Tidy up',
        p('Can we archive [name]? Check for open documents and wait for my OK.')),
    ],
    note: 'If two customers have similar names, E asks which one you mean. Archiving can be undone; E never permanently deletes customers.',
  },
  {
    id: 'layout', grp: 0, ic: 'layout', title: 'Document layout',
    lead: 'Redesign quotes and invoices. Preview first.',
    intro: 'You see a preview first. Nothing becomes your default without approval.',
    ok: 'Saving as your default',
    groups: [
      g('Preview',
        p('Show me our current quotation template.', { top: 1 }),
        p("Preview a quotation with a larger logo, a clear A4 item table and a highlighted total. Don't save it.", { top: 1 }),
        p('Preview an invoice with 40 line items and show the page breaks.')),
      g('Save',
        p('Set our invoice header logo to [logo] and add these payment instructions: [text]. After I approve the preview, save it as our default.', { top: 1 })),
      g('Check old documents',
        p("Show me that the already-issued invoice's PDF is unchanged.")),
    ],
    note: 'Every save is a new version and earlier ones are kept. Issued documents keep the layout they were issued with. Unknown details are left blank, never invented.',
  },
  {
    id: 'sales', grp: 0, ic: 'chart', title: 'Sales and stock',
    lead: 'Who owes you, what sells, what runs out.',
    intro: 'E reads your sales records. It changes only stock quantities, and only after you approve.',
    ok: 'Changing stock levels',
    groups: [
      g('Reports',
        p('For [start date] to [end date], report payments received, sales totals and unpaid balances.', { top: 1 }),
        p('Who still owes us money?', { top: 1 }),
        p('What is the status of invoice [number]?'),
        p('Answer this question about our sales: [question]. Show your filters.')),
      g('Stock and demand',
        p('Check stock for [product A] and [product B], then show upcoming demand and flag possible shortages.', { top: 1 }),
        p('Propose setting [product A] to [12] and [product B] to [7]. Change nothing until I approve.'),
        p('Restore the stock to what it was.')),
    ],
    note: 'E never edits invoices or marks them paid from here. If stock data is missing or a report fails, E says so, and it tells zero stock from no data.',
  },

  /* ===== Buy and spend ===== */
  {
    id: 'purchasing', grp: 1, ic: 'box', title: 'Purchasing and suppliers',
    lead: 'Supplier quote to purchase order to paid.',
    intro: 'E checks each step against the one before it.',
    ok: 'Issuing or cancelling an order, marking paid, voiding',
    groups: [
      g('Suppliers and paperwork',
        p('Find or save supplier [name]. Read the attached quotation and invoice and record the numbers, dates, lines and totals. Flag duplicates instead of guessing.', { top: 1, n: 'Attach the quotation and invoice' }),
        p("List this supplier's documents and history.")),
      g('Quotes and purchase orders',
        p('Accept supplier quote [number] and create a draft purchase order. Accepting must not buy anything.', { top: 1 }),
        p("Change the draft's delivery date to [date] and show the PDF."),
        p('Issue this purchase order.', { n: 'Admin only' }),
        p('Reject quote [number]: [reason].'),
        p('Cancel purchase order [number].', { n: 'Admin only' })),
      g('Deliveries',
        p('On [PO number], receive [2] units of line 1 and show what remains.'),
        p('Receive everything that is left.')),
      g('Supplier invoices',
        p("Check supplier invoice [number] against its purchase order and deliveries. Explain mismatches. Don't mark it paid.", { top: 1 }),
        p('Mark it disputed: line 1 is [RM150], the order says [RM120].'),
        p("Propose marking [number] as paid. I'll confirm."),
        p('Propose voiding [number] as a duplicate.')),
    ],
    note: 'Staff can prepare drafts; only an admin can issue, cancel, mark paid or void. E never makes a bank transfer, and cannot receive more than is outstanding.',
  },
  {
    id: 'expenses', grp: 1, ic: 'wallet', title: 'Expenses',
    lead: 'Snap receipts. File claims. Close the month.',
    intro: 'E files claims from your receipts. Staff see only their own.',
    ok: 'Approving, rejecting, closing a month',
    groups: [
      g('File a claim',
        p('File each attached receipt as its own claim, using the merchant, date, total and tax printed on it. Ask me if anything is unreadable.', { top: 1, n: 'Attach your receipts' }),
        p('File this expense with no receipt. Reason: [reason].'),
        p('File this receipt again.', { n: 'If already filed, E warns you' })),
      g('Check, fix, withdraw',
        p('List my claims.', { top: 1 }),
        p("Correct this claim's merchant to [name] and date to [date]."),
        p('Withdraw this claim.')),
      g('Review and reports',
        p('Approve this claim and reject that one because [reason].', { n: 'Admin only' }),
        p("Show this month's submissions with a draft PDF and CSV.", { top: 1, n: 'Admin only' }),
        p('Run our monthly mileage report.', { n: 'Admin only' })),
      g('Month end',
        p('What is our cutoff day? Propose changing it to the [25th].', { n: 'Admin only' }),
        p('Close this month once every claim is reviewed or carried forward, and give me the final PDF.', { n: 'Admin only' })),
    ],
    note: "Claims follow your cutoff cycle, not always the receipt's month. Staff cannot see colleagues' claims, approve their own or close a month, even by saying they are an admin. Closed months cannot be changed.",
  },
  {
    id: 'expense-rules', grp: 1, ic: 'sliders', title: 'Expense rules',
    lead: 'Set claim rules in plain words.',
    intro: 'Admins preview every rule change, apply it and undo it.',
    ok: 'Applying or undoing a rule',
    groups: [
      g('Look and preview',
        p('What kinds of expense rules can you set up?', { top: 1 }),
        p('Propose a [Mileage] category that needs distance and a route-map screenshot, with a cap of RM[amount]. Show one claim that passes and one that is blocked. Preview only.', { top: 1, n: 'Admin only' })),
      g('Apply and test',
        p('Apply exactly the changes you previewed.', { top: 1, n: 'Admin only' }),
        p('As a test, file one claim with a route map and one without. Is the rule enforced?')),
      g('Undo',
        p('Preview undoing the latest rule change.'),
        p('Preview removing just the [mileage cap].'),
        p('Preview resetting all the rules you created.')),
    ],
    note: 'Staff cannot change rules, and claiming to be an admin in chat changes nothing. Unsupported ideas, like reading distance from photos, go to your engineers. Undoing a rule never touches filed claims.',
  },

  /* ===== Run the business ===== */
  {
    id: 'company', grp: 2, ic: 'building', title: 'Company and team',
    lead: 'Company profile, people and logins.',
    intro: 'E saves only what you tell it and leaves the rest blank.',
    ok: 'Creating a login, changing defaults, any reset',
    groups: [
      g('Set up your company',
        p('How far along is our company setup?', { top: 1 }),
        p('Save these company details: [name], [country], [email], [phone], [address]. Leave tax and bank details empty.', { top: 1 }),
        p('What is still missing before we can issue invoices?'),
        p("Check our website [address] for our logo and suggest missing profile details. Keep what I've confirmed."),
        p('Pull any unsaved company details from this old invoice and show conflicts.', { n: 'Attach the invoice' })),
      g('People',
        p('Add [name] as a contact: [position], [department], [email]. No login.', { top: 1 }),
        p("Change [name]'s department to [department].", { n: 'Updates the same person' }),
        p('What does [name] need to get workspace access?'),
        p('Give [name] a login as an ordinary employee.', { n: 'Admin only' })),
      g('Before a reset',
        p("Show me what a company reset would delete. Don't run it.", { n: 'Resets use an owner form, never chat' })),
    ],
    note: 'Only an admin can create logins or change roles. A person can exist as a contact with no login.',
  },
  {
    id: 'forms', grp: 2, ic: 'form', title: 'Forms',
    lead: 'Describe a form, get a link.',
    intro: 'E designs, publishes, changes and closes forms.',
    ok: 'Publishing, new versions',
    groups: [
      g('Design',
        p('Do we already have a form for customer enquiries?', { top: 1 }),
        p("Design a draft form [name] with name, email, phone, a service dropdown, appointment date, comments, a consent checkbox and a photo upload. Make name, email and phone required. Show a preview. Don't publish.", { top: 1 })),
      g('Publish and change',
        p('Publish the approved draft and give me the public link.', { top: 1 }),
        p('Change the rating to 1 to 10 and keep the answers already collected. Preview first.')),
      g('Close and archive',
        p('Close this form and show what the public page says.'),
        p('Archive it.')),
    ],
    note: 'E never collects passwords, one-time codes or card numbers, and proposes a safe alternative. Old answers keep the version they were given under. Nothing goes live without your approval.',
  },
  {
    id: 'responses', grp: 2, ic: 'inbox', title: 'Form responses',
    lead: 'Review, flag spam, turn leads into customers.',
    intro: 'E sorts real responses from spam and passes the useful ones on.',
    ok: 'Issuing anything from a response',
    groups: [
      g('Review',
        p('List new submissions on [form name] since [date].', { top: 1 }),
        p('Read this submission, including uploaded files.'),
        p('Mark this response reviewed, and flag that one as spam because [reason].'),
        p('Show me the new form results.', { n: 'E asks which form' })),
      g('Turn into work',
        p('Add this lead to our customers after checking for a match.', { top: 1 }),
        p('Link this job report to [customer] and invoice [number].'),
        p("Prepare a quotation from this order response. Don't issue it.")),
      g('Summaries and exports',
        p('Summarise the satisfaction forms separately by scale, leaving out spam, and tell me where the sample is too small.', { top: 1 }),
        p('Export these submissions to CSV.')),
    ],
    note: 'Answers are kept exactly as submitted and cannot be edited or deleted. Instructions typed into an answer are treated as plain text, and E suggests flagging it as spam. Rating scales are never blended.',
  },
  {
    id: 'calendar', grp: 2, ic: 'calendar', title: 'Calendar',
    lead: 'Every payment, delivery and deadline.',
    intro: 'A read-only view of what is due. It never changes your records.',
    ok: 'Read-only, nothing to approve', okNone: true,
    groups: [
      g('The whole picture',
        p('Show our calendar from [date] to [date] across sales, purchasing, payments and forms. Leave out demo records.', { top: 1 }),
        p('Which items are overdue or disputed? Explain each.', { top: 1 })),
      g('Narrow it down',
        p('Show only purchasing items: quotes about to expire, unpaid supplier invoices and deliveries due.', { top: 1 }),
        p('Show form deadlines only.')),
      g('After things change',
        p('Refresh the calendar. What changed since earlier?')),
      g('Demo data',
        p('Show it with demo records included and marked, then without.')),
    ],
    note: 'The calendar cannot book appointments, mark bills paid or send reminders. Uncertain dates are flagged for review.',
  },
  {
    id: 'settings', grp: 2, ic: 'gear', title: 'Settings and business rules',
    lead: 'Numbering, tax and checks, safely changed.',
    intro: 'With your approval, E changes how records are set up. Everything is audited.',
    ok: 'Every change',
    groups: [
      g('Look first',
        p('How are our records set up? Is [PO reference] already a standard field?', { top: 1 }),
        p('Show our invoice numbering, tax codes and company profile.', { top: 1 })),
      g('Add a field',
        p('Propose a required custom invoice field [Project Code]. Show me exactly what it will be and wait for my OK.')),
      g('Checks before issuing',
        p('Show the checks an invoice must pass before issuing. Propose adding [check] as a warning and keep the must-haves.', { top: 1 })),
      g('Numbering and tax',
        p('Propose prefix [INV-] with [5]-digit padding and a yearly reset, without lowering the next number.')),
      g('History',
        p('Show the change history of [record] and who made each change.')),
    ],
    note: 'E will not reuse a number, remove must-have checks, change your database structure or delete audit history. It cannot decide which tax legally applies to you.',
  },

  /* ===== Show up online ===== */
  {
    id: 'web', grp: 3, ic: 'globe', title: 'Websites and prototypes',
    lead: 'Web pages and clickable prototypes.',
    intro: 'E builds in its own workspace and gives you a link. Prototypes use sample data.',
    ok: 'Recording your sign-off on a design',
    groups: [
      g('Web pages',
        p('Build a mobile-friendly landing page with a hero, three service cards, an FAQ and a contact section using [email] and our logo. Give me the link.', { top: 1 }),
        p("On that page, change only the hero heading to '[heading]' and the card accent to [colour]. Keep everything else.", { top: 1 }),
        p('Add our registration number to the footer.', { n: "E asks for the number if you haven't given it" })),
      g('Prototypes',
        p("Make a clickable prototype of [a project browser] with search and filters, in our app's style. Tell me what you assumed.", { top: 1 }),
        p('Add live cursors and a permission matrix. Label what is simulated and write up the gap for engineers.')),
      g('Sign-off',
        p("I accept this prototype as our department's design. Record the blueprint.")),
    ],
    note: "E works in its own workspace. It cannot touch your live system's code or other assistants' work; it records such requests for your engineers. Prototypes never claim to be live.",
  },
  {
    id: 'media', grp: 3, ic: 'image', title: 'Media kit',
    lead: 'Logos, photos and awards, partner-ready.',
    intro: 'Everything stays draft until you approve it.',
    ok: 'Publishing',
    groups: [
      g('Collect',
        p('Prepare our media kit from these files. Check what we already have, record titles, dates and sources from this list, and keep everything as draft.', { top: 1, n: 'Attach the files' }),
        p('Is this logo already in our media kit?')),
      g('Tidy',
        p("Correct this photo's title to [title] and caption to [caption]."),
        p('Keep this certificate as draft and tell me what source information is missing.')),
      g('Publish and share',
        p("Show these assets' details and status. Wait for my approval before publishing.", { top: 1 }),
        p('Give me a partner-ready list of the approved items and say which drafts were left out.', { top: 1 })),
      g('Archive',
        p('Archive this old photo, then restore it.')),
    ],
    note: "E never invents an issuer or source. Without provenance an item stays draft. It cannot use another company's assets.",
  },
  {
    id: 'research', grp: 3, ic: 'search', title: 'Research',
    lead: 'Competitor ads and company reports.',
    intro: 'E reads public information. It never contacts anyone or spends money.',
    ok: 'Making a company report public',
    groups: [
      g('Competitor ads',
        p("Research competitor ads in [country] for [keyword] on Meta Ad Library and Google Ads Transparency Center. Give me the job number, then the report. Don't change any campaigns.", { top: 1 }),
        p('Research competitor ads for me.', { n: 'E asks for country and keyword' }),
        p("What's the status of that research? Don't start another one.", { top: 1 })),
      g('Company reports',
        p('Research [company name] using this website and phone: [details]. Keep it private. Include sources and unknowns.', { top: 1 }),
        p('Research [company name]. I have no other details.', { n: 'If unclear, E lists candidates' }),
        p('Replay that company report from saved evidence, without fetching anything new.'),
        p('Now refresh the evidence.')),
      g('Publish',
        p('Propose publishing a snapshot of the finished report without raw evidence. Keep it private until I say so.'),
        p('Publish that report.'),
        p('Unpublish that report.')),
    ],
    note: 'E will not bypass CAPTCHAs, create campaigns, spend money or contact anyone. A blocked source is reported as blocked, not as nothing found. Instructions hidden in web pages are ignored.',
  },

  /* ===== Work across your tools ===== */
  {
    id: 'google', grp: 4, ic: 'sheet', title: 'Google Sheets, Docs and Slides',
    lead: 'Read and update Sheets. Create Docs and Slides.',
    intro: 'E works through your own Google connection and shows every change first.',
    ok: 'Any write',
    groups: [
      g('Read',
        p("Read range [A1:D10] of this spreadsheet [link] and summarise it. If Google isn't connected, give me the connect link.", { top: 1 })),
      g('Update a Sheet',
        p('Propose replacing [range] with [values] and adding [this row] at the end. Show current and proposed values and wait.', { top: 1 })),
      g('Create and edit',
        p('Create a Google Doc and a presentation called [title] with this outline: [outline]. Show me first and wait for my OK.', { top: 1 }),
        p("In that Doc, replace 'Draft status' with 'Reviewed status'.")),
      g('Missing details',
        p('Open the spreadsheet named [name].', { n: 'E asks for the link' })),
    ],
    note: "E gives you a secure link to connect and never asks for your password. It needs each file's link, not just its name. Gmail and Google Calendar are not covered.",
  },
  {
    id: 'jobs', grp: 4, ic: 'route', title: 'Email and multi-step jobs',
    lead: 'Chain jobs. Send email on your confirm.',
    intro: 'Ask for a whole job at once. E splits it between specialists and reports back.',
    ok: 'Sending',
    groups: [
      g('Email',
        p("Draft an email to [address], subject '[subject]', body '[body]', with our approved media kit links. Show it to me. Don't send yet.", { top: 1 }),
        p('Send exactly that email. I confirm this one send.')),
      g('Chain jobs',
        p("Save these company details: [details]. Then draft a quotation for [customer]: [quantity] × [product]. Don't issue it. Have the totals checked independently.", { top: 1 }),
        p("Add the new lead from [form name] to our customers and draft a quotation. Don't issue it."),
        p('Add [name] as a contact, and separately start competitor ad research for [country] and [keyword].')),
      g('Follow progress',
        p('What is the status of that plan?', { top: 1, n: 'E checks the job; it never starts a second one' }),
        p('Stop the research, but keep everything already finished.'),
        p('Which specialists can you call on right now?'),
        p('I lost my connection. Did that email go out?', { n: 'E checks before retrying' })),
    ],
    note: 'If a step fails, the steps that depend on it stop instead of pretending to succeed. If you change details after approving, E asks you to approve again.',
  },
];

export const STARTERS = [
  { t: 'Introduce your company', p: 'Save our company details: [name], [country], [email], [phone], [address]. What is still missing for invoicing?' },
  { t: 'See what is due', p: "Show this month's calendar. Explain anything overdue." },
  { t: 'Draft a quotation', p: "Draft a quotation for [customer]: [quantity] × [product]. Don't issue it." },
  { t: 'See who owes you', p: 'Who still owes us money?' },
  { t: 'Scan a name card', p: 'Record this name card as a customer. Check for duplicates first.', n: 'Attach a photo' },
  { t: 'Check competitor ads', p: 'Research competitor ads in [country] for [keyword].' },
];

export const LIMITS = [
  ['Act without your yes', 'Issuing, sending, publishing, paying, voiding and settings changes wait for your approval. Change the request and E asks again.'],
  ['Rewrite accounting history', 'Issued invoices stay as issued. Paid ones cannot be voided, and numbers are never reused. E offers void and replace, or a credit note.'],
  ['Move your money', 'E records payments. It makes no transfers, pays no supplier and spends nothing on ads.'],
  ["Go beyond someone's role", "Staff cannot see colleagues' claims, approve their own, issue purchase orders, change rules or close a month, whatever they type. One company's data never reaches another."],
  ['Cross the line with outsiders', 'No CAPTCHA bypass, no contacting the people it researches, no collecting passwords or card numbers.'],
  ['Make things up', 'Missing figures, unreadable files and blocked sources are reported as exactly that.'],
  ['Obey text hidden in your data', 'Instructions inside a note, form answer, cell, receipt or web page are treated as plain text.'],
  ['Change the system itself', 'No new database tables, code edits or code pushes. E records those requests for your engineers.'],
  ['Reach beyond its tools', 'No Gmail, appointment booking or calendar reminders.'],
];

/* Interface strings */
export const T = {
  lang: 'en',
  out: 'e-menu.html',
  title: "E's Menu",
  brand: "E's Menu",
  h1a: "Don't learn software.",
  h1b: 'Brief a teammate.',
  sub: 'Quotes, invoices, expenses, web pages, research. Just tell E what you need.',
  panelLabel: 'Example conversation',
  chat: {
    you1: 'Draft a quotation for ABC Sdn Bhd: two 450W solar panels.',
    e1a: 'Draft ready. Nothing issued yet.',
    item: '2 × 450W solar panel',
    price: 'RM200.00',
    e1b: 'Shall I issue it?',
    you2: 'Yes, issue it.',
  },
  chips: ['Type it like a message', 'Asks before it acts', "Says when it can't"],
  ctaPrimary: 'Try six easy requests',
  ctaSecondary: 'See everything E can do',
  startEyebrow: 'Start here',
  startH2: 'Six requests to try today',
  startLede: 'Tap Copy, swap the <span class="ph">[brackets]</span>, paste to E.',
  powerEyebrow: 'Everything E can do',
  powerH2: "What you can put on E's plate",
  powerLede: (n) => `${n} areas. Tap one, or search.`,
  searchPlaceholder: 'Search: invoice, expense, website...',
  searchLabel: 'Search the menu',
  habitsEyebrow: 'Three habits',
  habitsH2: 'Work with E like a sharp new colleague',
  habits: [
    ['Say the outcome', 'Add the names and numbers you know. E asks for the rest in one go.'],
    ['E drafts, you decide', 'Anything permanent waits for your yes.'],
    ['E tells the truth', 'Missing data or no permission? E says so.'],
  ],
  menuEyebrow: 'The full menu',
  menuH2: 'Ready-to-say requests, by area',
  limitsEyebrow: 'Know the limits',
  limitsH2: 'What E will not do',
  limitsLede: 'These protect your records, your money and your customers.',
  endH2: 'Not sure how to phrase it?',
  endPrompts: ['Can you help me with [what you need]?', 'What do you need from me to get this done?'],
  foot: 'Prepared 6 October 2026. Replace anything in [brackets] with your own details.',
  fab: 'All areas',
  more: (n) => `${n} more to say`,
  needsOk: 'Needs your OK: ',
  good: 'Good to know.',
  goodSep: ' ',
  otherHref: 'e-menu.zh.html',
  otherLang: 'zh-Hans',
  otherLabel: '简体中文',
  copyLabel: 'Copy this request',
  js: {
    copiedBracket: 'Copied. Replace the highlighted parts, then paste it to E.',
    copied: 'Copied. Paste it to E.',
    copyFail: 'Could not copy. Press and hold the text to copy it.',
    found1: '1 request found',
    foundN: '{n} requests found',
    first20: '. Showing the first 20.',
    none: 'Nothing matches. Try a shorter word such as invoice, expense or website.',
  },
  extraCss: '',
  fontHref: 'https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;500;600;700&family=Newsreader:opsz,wght@6..72,500;6..72,600&display=swap',
};
