import fs from 'node:fs/promises';
const path=new URL('./deck.html',import.meta.url);
let html=await fs.readFile(path,'utf8');
const sections=[...html.matchAll(/<section class="slide[^\"]*"[^>]*>[\s\S]*?<\/section>/g)].map(m=>m[0]);
const image=(name,alt,cls='')=>`<img class="artwork ${cls}" src="__${name.toUpperCase()}_IMAGE__" alt="${alt}">`;
const newBodies={
0:`${image('handoff','AI 数字员工向客户交付完成作品的概念图','full-bleed')}<div class="art-shade cover-shade"></div><p class="kicker">ETERNALGY AGENTIC AI</p><div class="hero-title"><h1>让 AI<br>把工作做完<span class="orange">。</span></h1><p class="hero-sub">快 · 好 · 美 · 省</p></div><p class="caption" style="left:99px;bottom:122px">从内部应用，走向市场</p><p class="art-credit">概念视觉</p>`,
4:`${image('owner','印刷工作室经营者查看手机的 AI 生成场景示意','owner-photo')}<p class="kicker">04 — 中小企业的使用门槛</p><h2 class="title" style="top:244px;font-size:96px;max-width:730px">老板没时间，<br>再学一套系统<span class="orange">。</span></h2><div class="three-words"><span>学习</span><span>适应</span><span>收尾</span></div><p class="caption" style="left:101px;bottom:139px">这些，都不该成为客户的负担。</p><p class="art-credit">场景示意</p>`,
7:`<p class="kicker">07 — 快好美省的实现基础</p><h2 class="title" style="top:142px;font-size:86px">细胞级设计。专业分工。</h2>${image('cells','四个相互连接的独立工作模块，分别代表资料研究、设计、执行与检查','cells-plate')}<div class="cell-labels"><span>资料</span><span>设计</span><span>执行</span><span>检查</span></div><p class="art-credit">专业分工概念示意</p>`,
9:`${image('malaysia','马来西亚中小商家街区的 AI 生成场景示意','full-bleed')}<div class="art-shade street-shade"></div><p class="kicker">09 — 马来西亚业务基础</p><h2 class="title" style="top:174px;font-size:115px">生于本地。<br>用在生意里。</h2><p class="local-context">TNB / Solar PV / WhatsApp / 销售与广告</p><div class="entry-offer"><span>首个商业入口</span><strong>AI 网站团队 ↗</strong></div><p class="art-credit">本地商业场景示意</p>`,
14:`${image('handoff','数字员工把完成的工作交到人手中的概念图','full-bleed closing-art')}<div class="art-shade closing-shade"></div><p class="kicker">ETERNALGY AGENTIC AI</p><h2 class="title" style="top:190px;font-size:110px">让每家企业，<br>拥有自己的<br>数字员工<span class="orange">。</span></h2><p class="closing-four">快 / 好 / 美 / 省</p><p class="art-credit">概念视觉</p>`
};
const updated=sections.map((s,i)=>{if(!(i in newBodies))return s;let open=s.slice(0,s.indexOf('>')+1);if(i===9||i===14)open=open.replace('keynote','image-dark keynote');const notes=s.match(/<aside class="speaker">([\s\S]*?)<\/aside>/)[1];return open+newBodies[i]+`<aside class="speaker">${notes} 本页使用内置 ImageGen 生成的概念或场景图片，用于解释主题，不是实际客户、实体机器人或产品架构实拍。真实网站证据在第3页。</aside></section>`});
html=html.replace(/<section class="slide[^\"]*"[\s\S]*?(?=\n<\/div><\/div><\/main>)/,updated.join('\n\n'));
html=html.replace('</style>',`
/* Image-led art direction. Generated context and actual evidence stay distinct. */
.artwork{position:absolute;display:block;object-fit:cover}.full-bleed{inset:0;width:1600px;height:1000px}.art-shade{position:absolute;inset:0;pointer-events:none}.cover-shade{background:linear-gradient(90deg,#f4f1e9 0%,#f4f1e9f8 24%,#f4f1e9bd 39%,#f4f1e900 64%)}.k1 .full-bleed{object-position:center}.k1 .hero-title{top:268px}.k1 .hero-title h1{font-size:125px;line-height:1.23;letter-spacing:-7px}.k1 .hero-sub{font-size:30px;margin-top:48px;letter-spacing:12px}.art-credit{position:absolute;bottom:73px;right:99px;font-size:13px;letter-spacing:1px;color:#746e61}.k1 .footer span:last-child{color:#6c6559}.owner-photo{top:0;left:830px;width:770px;height:1000px;object-position:center 42%}.k5 .three-words{top:660px;right:auto;gap:72px;font-size:27px}.k5 .art-credit{color:#fff;text-shadow:0 1px 5px #000}.k5 .footer span:last-child{color:#fff}.cells-plate{left:90px;top:271px;width:1420px;height:518px;object-fit:cover;object-position:center 48%;mix-blend-mode:multiply}.cell-labels{position:absolute;left:100px;right:100px;top:812px;display:grid;grid-template-columns:repeat(4,1fr);font-size:29px;text-align:center;color:#44463e}.k8 .art-credit{bottom:76px}.image-dark{color:#fcf8ee;background:#292722}.image-dark .kicker{color:#ece6da}.image-dark .footer,.image-dark .footer span:first-child{color:#e2dace}.image-dark .art-credit{color:#d9d3c9}.street-shade{background:linear-gradient(180deg,#1719144d 0%,#17191408 43%,#171914e3 78%,#171914f5 100%)}.k10 .title{font-weight:600;text-shadow:0 3px 24px #18191080}.local-context{position:absolute;left:100px;top:699px;font-size:23px;color:#ddd7cc;letter-spacing:1px}.k10 .entry-offer{top:764px;border-color:#b8b2a466}.k10 .entry-offer span{color:#dfd8c9}.k10 .entry-offer strong{color:#f3be91;font-size:49px}.closing-art{object-position:center}.closing-shade{background:linear-gradient(90deg,#161a17f5 0%,#161a17d9 31%,#161a1769 57%,#161a1712 100%)}.k15 .title{font-weight:600;letter-spacing:-5px}.k15 .orange{color:#ed9d71!important}.k15 .closing-four{color:#eab38a}.k15 .footer span:last-child{color:#e8e0d4}
</style>`);
await fs.writeFile(path,html);
console.log('Image-led cover, SME scene, specialist architecture, local market, and closing integrated.');
